export const criteriosData = [
    {
        "N°": 1,
        "Activo": "Base de datos de clientes y proveedores",
        "Probabilidad": "Medio",
        "Impacto Financiero": "Alto",
        "Impacto Legal": "Alto",
        "Impacto Reputacional": "Alto",
        "Justificación": "Riesgo alto de ataque que podría comprometer datos personales y comerciales, afectando la confianza y generando sanciones.",
        "Controles a Implementar": "5.9: Inventario de información y otros activos asociados - Registrar y clasificar este activo crítico.\n5.15: Control de acceso - Limitar el acceso solo a personal autorizado.\n8.12: Prevención de fuga de datos - Implementar medidas para evitar que los datos se filtren externamente.",
        "Color Probabilidad": "Amarillo",
        "Color Impacto Financiero": "Rojo",
        "Color Impacto Legal": "Rojo",
        "Color Impacto Reputacional": "Rojo"
    },
    {
        "N°": 2,
        "Activo": "Registros financieros y contables",
        "Probabilidad": "Bajo",
        "Impacto Financiero": "Medio",
        "Impacto Legal": "Alto",
        "Impacto Reputacional": "Medio",
        "Justificación": "Compromete datos financieros sensibles, con riesgo de sanciones legales y daño reputacional si se filtran.",
        "Controles a Implementar": "5.33: Protección de registros - Asegurar la integridad y disponibilidad de los registros financieros.\n8.7: Protección contra malware - Proteger los sistemas donde se almacenan los registros.\n5.34: Privacidad y protección de la PII - Proteger los datos personales dentro de los registros.",
        "Color Probabilidad": "Verde",
        "Color Impacto Financiero": "Amarillo",
        "Color Impacto Legal": "Rojo",
        "Color Impacto Reputacional": "Amarillo"
    },
    {
        "N°": 3,
        "Activo": "Documentación administrativa",
        "Probabilidad": "Bajo",
        "Impacto Financiero": "Bajo",
        "Impacto Legal": "Medio",
        "Impacto Reputacional": "Bajo",
        "Justificación": "Contiene políticas y contratos; pérdida o acceso no autorizado podría causar un impacto legal y operativo moderado.",
        "Controles a Implementar": "5.10: Uso aceptable de la información y otros activos asociados - Definir pautas para el uso de esta documentación.\n5.12: Clasificación de la información - Clasificar la documentación según su sensibilidad.\n7.7: Limpiar escritorio y limpiar pantalla - Implementar políticas para reducir el riesgo de exposición de documentos en áreas compartidas.",
        "Color Probabilidad": "Verde",
        "Color Impacto Financiero": "Verde",
        "Color Impacto Legal": "Amarillo",
        "Color Impacto Reputacional": "Verde"
    },
    {
        "N°": 4,
        "Activo": "Plan de negocio y estrategias de marketing",
        "Probabilidad": "Medio",
        "Impacto Financiero": "Medio",
        "Impacto Legal": "Bajo",
        "Impacto Reputacional": "Medio",
        "Justificación": "Su pérdida afecta la competitividad y la estrategia empresarial, aunque el impacto legal es limitado.",
        "Controles a Implementar": "5.1: Políticas de seguridad de la información - Incluir el plan de negocio y marketing en las políticas de seguridad.\n5.10: Uso aceptable de la información y otros activos asociados - Asegurar un uso adecuado de este activo.\n8.10: Eliminación de información - Definir procesos seguros de eliminación cuando se actualice o deseche.",
        "Color Probabilidad": "Amarillo",
        "Color Impacto Financiero": "Amarillo",
        "Color Impacto Legal": "Verde",
        "Color Impacto Reputacional": "Amarillo"
    },
    {
        "N°": 5,
        "Activo": "Información de procesos y procedimientos operativos",
        "Probabilidad": "Bajo",
        "Impacto Financiero": "Bajo",
        "Impacto Legal": "Bajo",
        "Impacto Reputacional": "Bajo",
        "Justificación": "La divulgación afecta la eficiencia interna, pero el riesgo legal y financiero es bajo.",
        "Controles a Implementar": "5.37: Procedimientos operativos documentados - Mantener documentación de los procesos y procedimientos.\n5.4: Responsabilidades de la gerencia - Definir claramente las responsabilidades en los procesos.\n7.14: Eliminación segura o reutilización del equipo - Asegurar la eliminación segura de equipos donde se almacenen procedimientos obsoletos.",
        "Color Probabilidad": "Verde",
        "Color Impacto Financiero": "Verde",
        "Color Impacto Legal": "Verde",
        "Color Impacto Reputacional": "Verde"
    },
    {
        "N°": 6,
        "Activo": "Registros de recursos humanos",
        "Probabilidad": "Medio",
        "Impacto Financiero": "Medio",
        "Impacto Legal": "Medio",
        "Impacto Reputacional": "Medio",
        "Justificación": "Contiene datos personales de empleados, con impacto financiero y legal en caso de filtración o pérdida.",
        "Controles a Implementar": "6.6: Acuerdos de confidencialidad o no divulgación - Proteger los datos de empleados a través de NDAs.\n5.34: Privacidad y protección de la PII - Garantizar la privacidad de los datos personales.\n8.10: Eliminación de información - Definir procedimientos de eliminación segura de registros de empleados.",
        "Color Probabilidad": "Amarillo",
        "Color Impacto Financiero": "Amarillo",
        "Color Impacto Legal": "Amarillo",
        "Color Impacto Reputacional": "Amarillo"
    },
    {
        "N°": 7,
        "Activo": "Registros históricos de ventas y compras",
        "Probabilidad": "Bajo",
        "Impacto Financiero": "Bajo",
        "Impacto Legal": "Bajo",
        "Impacto Reputacional": "Bajo",
        "Justificación": "Útil para análisis y estrategias, pero su pérdida no representa un alto riesgo legal ni financiero.",
        "Controles a Implementar": "5.33: Protección de registros - Proteger la integridad de estos datos históricos.\n8.13: Copia de seguridad de la información - Asegurar que estos registros tengan respaldo.\n5.9: Inventario de información y otros activos asociados - Incluir estos registros en el inventario de información.",
        "Color Probabilidad": "Verde",
        "Color Impacto Financiero": "Verde",
        "Color Impacto Legal": "Verde",
        "Color Impacto Reputacional": "Verde"
    },
    {
        "N°": 8,
        "Activo": "Registros de gestión de inventarios",
        "Probabilidad": "Bajo",
        "Impacto Financiero": "Medio",
        "Impacto Legal": "Bajo",
        "Impacto Reputacional": "Bajo",
        "Justificación": "Afecta la operatividad y control de existencias; un incidente impacta las finanzas pero es poco relevante legalmente.",
        "Controles a Implementar": "8.22: Segregación de redes - Asegurar que el sistema de gestión de inventarios esté en una red segregada para mayor seguridad.\n5.9: Inventario de información y otros activos asociados - Clasificar y mantener el control de este activo.\n8.10: Eliminación de información - Establecer medidas de eliminación segura para datos obsoletos.",
        "Color Probabilidad": "Verde",
        "Color Impacto Financiero": "Amarillo",
        "Color Impacto Legal": "Verde",
        "Color Impacto Reputacional": "Verde"
    },
    {
        "N°": 9,
        "Activo": "Software de gestión empresarial (ERP, CRM)",
        "Probabilidad": "Medio",
        "Impacto Financiero": "Alto",
        "Impacto Legal": "Medio",
        "Impacto Reputacional": "Bajo",
        "Justificación": "Afecta la operación directa, con impacto financiero alto si falla; riesgo reputacional y legal moderado.",
        "Controles a Implementar": "8.25: Ciclo de vida de desarrollo seguro - Aplicar controles de seguridad en el desarrollo y actualización del software.\n8.27: Principios de ingeniería y arquitectura de sistemas seguros - Diseñar el software con seguridad integrada.\n8.31: Separación de los entornos de desarrollo, prueba y producción - Asegurar que el software esté adecuadamente aislado.",
        "Color Probabilidad": "Amarillo",
        "Color Impacto Financiero": "Rojo",
        "Color Impacto Legal": "Amarillo",
        "Color Impacto Reputacional": "Verde"
    },
    {
        "N°": 10,
        "Activo": "Correo electrónico corporativo",
        "Probabilidad": "Alto",
        "Impacto Financiero": "Bajo",
        "Impacto Legal": "Medio",
        "Impacto Reputacional": "Medio",
        "Justificación": "Alta probabilidad de ataques; su compromiso afecta comunicación interna y externa, con impacto legal y reputacional moderado.",
        "Controles a Implementar": "8.7: Protección contra malware - Proteger el sistema de correo contra malware y phishing.\n5.15: Control de acceso - Limitar acceso al correo corporativo a usuarios autorizados.\n8.18: Uso de programas de utilidad privilegiados - Monitorear el uso de herramientas de administración en el sistema de correo.",
        "Color Probabilidad": "Rojo",
        "Color Impacto Financiero": "Verde",
        "Color Impacto Legal": "Amarillo",
        "Color Impacto Reputacional": "Amarillo"
    },
    {
        "N°": 11,
        "Activo": "Almacenamiento de datos en nube/servidores",
        "Probabilidad": "Medio",
        "Impacto Financiero": "Alto",
        "Impacto Legal": "Alto",
        "Impacto Reputacional": "Medio",
        "Justificación": "Su pérdida afecta a todos los datos de la empresa, con consecuencias legales y financieras graves.",
        "Controles a Implementar": "8.23: Seguridad de la información para el uso de servicios en la nube - Proteger la información en almacenamiento en la nube.\n8.20: Seguridad de redes - Asegurar las conexiones de red hacia y desde el almacenamiento.\n8.13: Copia de seguridad de la información - Mantener copias de seguridad de los datos críticos.",
        "Color Probabilidad": "Amarillo",
        "Color Impacto Financiero": "Rojo",
        "Color Impacto Legal": "Rojo",
        "Color Impacto Reputacional": "Amarillo"
    },
    {
        "N°": 12,
        "Activo": "Sitio web",
        "Probabilidad": "Medio",
        "Impacto Financiero": "Bajo",
        "Impacto Legal": "Bajo",
        "Impacto Reputacional": "Medio",
        "Justificación": "Su caída afecta la imagen de la empresa y la percepción pública, pero el riesgo financiero y legal es bajo.",
        "Controles a Implementar": "8.21: Seguridad de los servicios de red - Proteger el sitio web contra ataques.\n8.24: Uso de criptografía - Utilizar cifrado para las comunicaciones y autenticación del sitio.\n8.28: Codificación segura - Asegurar que el código del sitio web cumpla con estándares de seguridad.",
        "Color Probabilidad": "Amarillo",
        "Color Impacto Financiero": "Verde",
        "Color Impacto Legal": "Verde",
        "Color Impacto Reputacional": "Amarillo"
    },
    {
        "N°": 13,
        "Activo": "Redes sociales",
        "Probabilidad": "Alto",
        "Impacto Financiero": "Bajo",
        "Impacto Legal": "Bajo",
        "Impacto Reputacional": "Medio",
        "Justificación": "Frecuentemente atacadas; una brecha afecta la reputación, aunque el impacto financiero y legal es menor.",
        "Controles a Implementar": "5.34: Privacidad y protección de la PII - Proteger los datos personales compartidos en redes sociales.\n6.3: Concientización, educación y capacitación sobre seguridad de la información - Capacitar al personal en el uso seguro de redes sociales.\n8.16: Actividades de seguimiento - Monitorizar las redes sociales para detectar incidentes de seguridad.",
        "Color Probabilidad": "Rojo",
        "Color Impacto Financiero": "Verde",
        "Color Impacto Legal": "Verde",
        "Color Impacto Reputacional": "Amarillo"
    },
    {
        "N°": 14,
        "Activo": "Sistemas de videoconferencia o mensajería",
        "Probabilidad": "Alto",
        "Impacto Financiero": "Bajo",
        "Impacto Legal": "Medio",
        "Impacto Reputacional": "Medio",
        "Justificación": "Vulnerables a ataques; comprometen comunicaciones confidenciales, impactando la confianza y legalidad.",
        "Controles a Implementar": "8.5: Autenticación segura - Asegurar el acceso seguro a las plataformas de videoconferencia y mensajería.\n5.15: Control de acceso - Limitar el uso de estas herramientas a usuarios autorizados.\n8.20: Seguridad de redes - Asegurar la conexión de red para evitar escuchas no autorizadas.",
        "Color Probabilidad": "Rojo",
        "Color Impacto Financiero": "Verde",
        "Color Impacto Legal": "Amarillo",
        "Color Impacto Reputacional": "Amarillo"
    },
    {
        "N°": 15,
        "Activo": "Contraseñas y autenticación",
        "Probabilidad": "Muy Alto",
        "Impacto Financiero": "Alto",
        "Impacto Legal": "Alto",
        "Impacto Reputacional": "Alto",
        "Justificación": "Su vulneración afecta todos los sistemas; alta probabilidad de ataque y graves consecuencias financieras y reputacionales.",
        "Controles a Implementar": "8.5: Autenticación segura - Asegurar que las contraseñas cumplan con criterios de seguridad.\n5.17: Información de autenticación - Gestionar y proteger la información de autenticación.\n8.24: Uso de criptografía - Utilizar cifrado para almacenar y proteger contraseñas.",
        "Color Probabilidad": "Rojo",
        "Color Impacto Financiero": "Rojo",
        "Color Impacto Legal": "Rojo",
        "Color Impacto Reputacional": "Rojo"
    },
    {
        "N°": 16,
        "Activo": "Software de seguridad y antivirus",
        "Probabilidad": "Alto",
        "Impacto Financiero": "Alto",
        "Impacto Legal": "Medio",
        "Impacto Reputacional": "Medio",
        "Justificación": "Compromete la protección de otros sistemas, con alto impacto financiero y legal si es vulnerado.",
        "Controles a Implementar": "8.7: Protección contra malware - Implementar software de antivirus y antimalware para proteger los sistemas.\n8.8: Gestión de vulnerabilidades técnicas - Asegurar que el software de seguridad esté actualizado.\n8.18: Uso de programas de utilidad privilegiados - Controlar el acceso a las herramientas de seguridad.",
        "Color Probabilidad": "Rojo",
        "Color Impacto Financiero": "Rojo",
        "Color Impacto Legal": "Amarillo",
        "Color Impacto Reputacional": "Amarillo"
    },
    {
        "N°": 17,
        "Activo": "Sistemas de respaldo de información",
        "Probabilidad": "Medio",
        "Impacto Financiero": "Alto",
        "Impacto Legal": "Medio",
        "Impacto Reputacional": "Bajo",
        "Justificación": "Su falla implica la pérdida de datos críticos, afectando la operatividad y generando riesgos financieros.",
        "Controles a Implementar": "8.13: Copia de seguridad de la información - Mantener copias de seguridad periódicas.\n8.14: Redundancia de las instalaciones de procesamiento de información - Asegurar redundancia en los sistemas de respaldo.\n5.29: Seguridad de la información durante una interrupción - Garantizar que la información esté disponible durante una interrupción.",
        "Color Probabilidad": "Amarillo",
        "Color Impacto Financiero": "Rojo",
        "Color Impacto Legal": "Amarillo",
        "Color Impacto Reputacional": "Verde"
    },
    {
        "N°": 18,
        "Activo": "Terminales de punto de venta (POS)",
        "Probabilidad": "Medio",
        "Impacto Financiero": "Medio",
        "Impacto Legal": "Medio",
        "Impacto Reputacional": "Medio",
        "Justificación": "Impacta ventas directas; el compromiso de datos financieros genera riesgos legales y financieros moderados.",
        "Controles a Implementar": "8.1: Dispositivos terminales de usuario - Asegurar el control de los dispositivos POS.\n5.16: Gestión de identidad - Controlar las identidades y permisos en los dispositivos POS.\n8.20: Seguridad de redes - Proteger las conexiones de red de los POS.",
        "Color Probabilidad": "Amarillo",
        "Color Impacto Financiero": "Amarillo",
        "Color Impacto Legal": "Amarillo",
        "Color Impacto Reputacional": "Amarillo"
    },
    {
        "N°": 19,
        "Activo": "Computadoras y dispositivos de oficina",
        "Probabilidad": "Medio",
        "Impacto Financiero": "Medio",
        "Impacto Legal": "Medio",
        "Impacto Reputacional": "Medio",
        "Justificación": "Son esenciales para las operaciones; comprometen seguridad de datos y afectan la continuidad operativa.",
        "Controles a Implementar": "8.1: Dispositivos terminales de usuario - Implementar controles de seguridad en los dispositivos.\n8.7: Protección contra malware - Proteger contra virus y malware.\n5.11: Devolución de activos - Asegurar la devolución y el manejo seguro de los dispositivos.",
        "Color Probabilidad": "Amarillo",
        "Color Impacto Financiero": "Amarillo",
        "Color Impacto Legal": "Amarillo",
        "Color Impacto Reputacional": "Amarillo"
    },
    {
        "N°": 20,
        "Activo": "Equipos especializados o maquinaria",
        "Probabilidad": "Bajo",
        "Impacto Financiero": "Alto",
        "Impacto Legal": "Bajo",
        "Impacto Reputacional": "Bajo",
        "Justificación": "Afecta directamente la producción o servicio, con impacto financiero alto en caso de falla o pérdida.",
        "Controles a Implementar": "7.8: Ubicación y protección del equipo - Asegurar la ubicación y el acceso seguro a los equipos.\n8.19: Instalación de software en sistemas operativos - Controlar el software en los equipos especializados.\n7.13: Mantenimiento del equipo - Asegurar el mantenimiento regular para evitar fallos.",
        "Color Probabilidad": "Verde",
        "Color Impacto Financiero": "Rojo",
        "Color Impacto Legal": "Verde",
        "Color Impacto Reputacional": "Verde"
    },
    {
        "N°": 21,
        "Activo": "Mobiliario de oficina",
        "Probabilidad": "Muy Bajo",
        "Impacto Financiero": "Muy Bajo",
        "Impacto Legal": "Muy Bajo",
        "Impacto Reputacional": "Muy Bajo",
        "Justificación": "Poco impacto en operaciones y sin implicaciones legales; de bajo valor y relevancia en la imagen pública.",
        "Controles a Implementar": "7.3: Protección de oficinas, habitaciones e instalaciones - Asegurar la protección de los muebles y equipos dentro de las instalaciones.\n5.10: Uso aceptable de la información y otros activos asociados - Definir el uso adecuado de los activos para evitar daños.\n7.14: Eliminación segura o reutilización del equipo - Asegurar que el mobiliario que contiene activos de información sea eliminado o reutilizado de forma segura.",
        "Color Probabilidad": "Verde",
        "Color Impacto Financiero": "Verde",
        "Color Impacto Legal": "Verde",
        "Color Impacto Reputacional": "Verde"
    },
    {
        "N°": 22,
        "Activo": "Vehículos de distribución o logística",
        "Probabilidad": "Medio",
        "Impacto Financiero": "Medio",
        "Impacto Legal": "Bajo",
        "Impacto Reputacional": "Bajo",
        "Justificación": "Su pérdida afecta la distribución, con impacto financiero moderado y relevancia limitada en el ámbito legal y reputacional.",
        "Controles a Implementar": "5.9: Inventario de información y otros activos asociados - Mantener un inventario actualizado de los vehículos utilizados para distribución.\n7.9: Seguridad de los activos fuera de las instalaciones - Proteger los vehículos y sus contenidos, especialmente cuando están en tránsito.\n7.5: Protección contra amenazas físicas y ambientales - Proteger los vehículos contra riesgos físicos y ambientales.",
        "Color Probabilidad": "Amarillo",
        "Color Impacto Financiero": "Amarillo",
        "Color Impacto Legal": "Verde",
        "Color Impacto Reputacional": "Verde"
    },
    {
        "N°": 23,
        "Activo": "Dispositivos móviles",
        "Probabilidad": "Medio",
        "Impacto Financiero": "Medio",
        "Impacto Legal": "Medio",
        "Impacto Reputacional": "Medio",
        "Justificación": "Almacenan datos de negocio; pérdida o acceso no autorizado genera riesgos financieros y reputacionales.",
        "Controles a Implementar": "8.1: Dispositivos terminales de usuario - Implementar controles de seguridad para dispositivos móviles.\n8.12: Prevención de fuga de datos - Asegurar que los datos almacenados en dispositivos móviles estén protegidos contra pérdida o robo.\n8.10: Eliminación de información - Garantizar que los datos se eliminen de forma segura en caso de reemplazo o pérdida del dispositivo.",
        "Color Probabilidad": "Amarillo",
        "Color Impacto Financiero": "Amarillo",
        "Color Impacto Legal": "Amarillo",
        "Color Impacto Reputacional": "Amarillo"
    },
    {
        "N°": 24,
        "Activo": "Cámaras de vigilancia",
        "Probabilidad": "Bajo",
        "Impacto Financiero": "Bajo",
        "Impacto Legal": "Bajo",
        "Impacto Reputacional": "Bajo",
        "Justificación": "Útiles para seguridad física, pero con bajo impacto financiero y reputacional si fallan.",
        "Controles a Implementar": "7.4: Monitoreo de seguridad física - Asegurar que las cámaras estén instaladas y monitoreadas para cubrir áreas críticas.\n7.1: Perímetros de seguridad física - Colocar las cámaras en ubicaciones estratégicas para proteger el perímetro físico.\n7.8: Ubicación y protección del equipo - Proteger las cámaras para asegurar su funcionamiento y evitar vandalismo.",
        "Color Probabilidad": "Verde",
        "Color Impacto Financiero": "Verde",
        "Color Impacto Legal": "Verde",
        "Color Impacto Reputacional": "Verde"
    },
    {
        "N°": 25,
        "Activo": "Sistemas de acceso físico controlado",
        "Probabilidad": "Bajo",
        "Impacto Financiero": "Bajo",
        "Impacto Legal": "Bajo",
        "Impacto Reputacional": "Bajo",
        "Justificación": "Riesgo bajo; control de acceso físico es básico pero no crítico financieramente ni reputacionalmente.",
        "Controles a Implementar": "7.2: Entrada física - Controlar el acceso físico a las instalaciones a través de sistemas seguros.\n7.6: Trabajar en áreas seguras - Asegurar que los sistemas de acceso sean efectivos en áreas de alta seguridad.\n5.15: Control de acceso - Definir políticas y procedimientos de acceso para el personal autorizado.",
        "Color Probabilidad": "Verde",
        "Color Impacto Financiero": "Verde",
        "Color Impacto Legal": "Verde",
        "Color Impacto Reputacional": "Verde"
    },
    {
        "N°": 26,
        "Activo": "Suministros y materiales de operación diaria",
        "Probabilidad": "Muy Bajo",
        "Impacto Financiero": "Muy Bajo",
        "Impacto Legal": "Muy Bajo",
        "Impacto Reputacional": "Muy Bajo",
        "Justificación": "Su pérdida no afecta significativamente la operación o la reputación, y tiene un bajo impacto legal.",
        "Controles a Implementar": "5.9: Inventario de información y otros activos asociados - Mantener un inventario de los suministros y materiales.\n7.8: Ubicación y protección del equipo - Asegurar que los suministros estén bien ubicados y protegidos en áreas de almacenamiento.\n5.10: Uso aceptable de la información y otros activos asociados - Establecer pautas de uso adecuado para minimizar pérdidas.",
        "Color Probabilidad": "Verde",
        "Color Impacto Financiero": "Verde",
        "Color Impacto Legal": "Verde",
        "Color Impacto Reputacional": "Verde"
    },
    {
        "N°": 27,
        "Activo": "Almacenes o depósitos",
        "Probabilidad": "Bajo",
        "Impacto Financiero": "Medio",
        "Impacto Legal": "Bajo",
        "Impacto Reputacional": "Bajo",
        "Justificación": "Afecta el almacenamiento de productos, con impacto financiero moderado en caso de pérdida o daño.",
        "Controles a Implementar": "7.3: Protección de oficinas, habitaciones e instalaciones - Proteger los almacenes donde se guardan productos o materiales críticos.\n7.1: Perímetros de seguridad física - Asegurar un perímetro seguro para los almacenes.\n5.9: Inventario de información y otros activos asociados - Llevar un inventario de los productos almacenados.",
        "Color Probabilidad": "Verde",
        "Color Impacto Financiero": "Amarillo",
        "Color Impacto Legal": "Verde",
        "Color Impacto Reputacional": "Verde"
    },
    {
        "N°": 28,
        "Activo": "Personal operativo y administrativo",
        "Probabilidad": "Medio",
        "Impacto Financiero": "Medio",
        "Impacto Legal": "Bajo",
        "Impacto Reputacional": "Medio",
        "Justificación": "Su rotación o pérdida afecta las operaciones y la imagen interna, pero el impacto financiero y legal es limitado.",
        "Controles a Implementar": "6.1: Detección - Realizar evaluaciones de antecedentes antes de contratar personal.\n6.3: Concientización, educación y capacitación sobre seguridad de la información - Capacitar al personal sobre buenas prácticas de seguridad.\n6.2: Términos y condiciones de empleo - Establecer condiciones de empleo que incluyan requisitos de seguridad de la información.",
        "Color Probabilidad": "Amarillo",
        "Color Impacto Financiero": "Amarillo",
        "Color Impacto Legal": "Verde",
        "Color Impacto Reputacional": "Amarillo"
    },
    {
        "N°": 29,
        "Activo": "Capacitaciones y entrenamiento",
        "Probabilidad": "Bajo",
        "Impacto Financiero": "Bajo",
        "Impacto Legal": "Bajo",
        "Impacto Reputacional": "Bajo",
        "Justificación": "No afecta significativamente la operación directa o la reputación de la empresa.",
        "Controles a Implementar": "6.3: Concientización, educación y capacitación sobre seguridad de la información - Implementar programas de capacitación en seguridad.\n5.36: Cumplimiento de políticas, reglas y estándares de seguridad de la Información - Asegurarse de que las políticas de seguridad se incluyan en las capacitaciones.\n5.35: Revisión independiente de la seguridad de la información - Evaluar regularmente la efectividad de los programas de capacitación.",
        "Color Probabilidad": "Verde",
        "Color Impacto Financiero": "Verde",
        "Color Impacto Legal": "Verde",
        "Color Impacto Reputacional": "Verde"
    },
    {
        "N°": 30,
        "Activo": "Acuerdos de confidencialidad y no divulgación",
        "Probabilidad": "Bajo",
        "Impacto Financiero": "Medio",
        "Impacto Legal": "Alto",
        "Impacto Reputacional": "Medio",
        "Justificación": "Su incumplimiento afecta la privacidad y seguridad de la información, generando riesgos legales.",
        "Controles a Implementar": "6.6: Acuerdos de confidencialidad o no divulgación - Asegurarse de que todo el personal y los proveedores firmen acuerdos de confidencialidad.\n5.34: Privacidad y protección de la PII - Asegurar que los acuerdos cubran la privacidad y la protección de datos personales.\n5.31: Requisitos legales, estatutarios, reglamentarios y contractuales - Verificar que los acuerdos cumplan con las leyes aplicables.",
        "Color Probabilidad": "Verde",
        "Color Impacto Financiero": "Amarillo",
        "Color Impacto Legal": "Rojo",
        "Color Impacto Reputacional": "Amarillo"
    },
    {
        "N°": 31,
        "Activo": "Políticas de uso aceptable de activos",
        "Probabilidad": "Bajo",
        "Impacto Financiero": "Bajo",
        "Impacto Legal": "Bajo",
        "Impacto Reputacional": "Bajo",
        "Justificación": "Riesgo bajo, aunque su ausencia podría afectar la cultura de seguridad interna de la empresa.",
        "Controles a Implementar": "5.10: Uso aceptable de la información y otros activos asociados - Definir y comunicar las políticas de uso aceptable.\n5.36: Cumplimiento de políticas, reglas y estándares de seguridad de la Información - Monitorear el cumplimiento de la política de uso aceptable.\n6.3: Concientización, educación y capacitación sobre seguridad de la información - Incluir la política de uso aceptable en las capacitaciones.",
        "Color Probabilidad": "Verde",
        "Color Impacto Financiero": "Verde",
        "Color Impacto Legal": "Verde",
        "Color Impacto Reputacional": "Verde"
    },
    {
        "N°": 32,
        "Activo": "Clientes recurrentes",
        "Probabilidad": "Medio",
        "Impacto Financiero": "Medio",
        "Impacto Legal": "Bajo",
        "Impacto Reputacional": "Medio",
        "Justificación": "Importantes para la estabilidad; su pérdida afecta finanzas y reputación, aunque el impacto legal es menor.",
        "Controles a Implementar": "5.34: Privacidad y protección de la PII - Proteger la información de los clientes recurrentes.\n5.9: Inventario de información y otros activos asociados - Mantener un inventario actualizado de los clientes y su información.\n5.20: Abordar la seguridad de la información en los acuerdos con proveedores - Asegurar que los proveedores que interactúan con clientes cumplan con las políticas de seguridad.",
        "Color Probabilidad": "Amarillo",
        "Color Impacto Financiero": "Amarillo",
        "Color Impacto Legal": "Verde",
        "Color Impacto Reputacional": "Amarillo"
    },
    {
        "N°": 33,
        "Activo": "Proveedores estratégicos",
        "Probabilidad": "Medio",
        "Impacto Financiero": "Medio",
        "Impacto Legal": "Bajo",
        "Impacto Reputacional": "Medio",
        "Justificación": "Su pérdida afecta la operación y finanzas, aunque el impacto legal y reputacional es moderado.",
        "Controles a Implementar": "5.19: Seguridad de la información en las relaciones con proveedores - Asegurar que los proveedores estratégicos cumplan con los requisitos de seguridad.\n5.20: Abordar la seguridad de la información en los acuerdos con proveedores - Definir y gestionar los acuerdos de seguridad con proveedores estratégicos.\n5.22: Monitoreo, revisión y gestión de cambios de servicios de proveedores - Supervisar y revisar la seguridad de los servicios de los proveedores.",
        "Color Probabilidad": "Amarillo",
        "Color Impacto Financiero": "Amarillo",
        "Color Impacto Legal": "Verde",
        "Color Impacto Reputacional": "Amarillo"
    },
    {
        "N°": 34,
        "Activo": "Reputación de marca y fidelización",
        "Probabilidad": "Medio",
        "Impacto Financiero": "Medio",
        "Impacto Legal": "Bajo",
        "Impacto Reputacional": "Alto",
        "Justificación": "Afecta la percepción pública de la empresa; cualquier evento de riesgo impacta directamente su imagen.",
        "Controles a Implementar": "5.7: Inteligencia sobre amenazas - Monitorear amenazas que puedan afectar la reputación de la marca.\n5.27: Aprender de los incidentes de seguridad de la información - Revisar y aprender de incidentes que afecten la imagen de la empresa.\n6.3: Concientización, educación y capacitación sobre seguridad de la información - Capacitar al personal sobre la importancia de proteger la imagen de la empresa.",
        "Color Probabilidad": "Amarillo",
        "Color Impacto Financiero": "Amarillo",
        "Color Impacto Legal": "Verde",
        "Color Impacto Reputacional": "Rojo"
    },
    {
        "N°": 35,
        "Activo": "Alianzas comerciales",
        "Probabilidad": "Bajo",
        "Impacto Financiero": "Bajo",
        "Impacto Legal": "Bajo",
        "Impacto Reputacional": "Medio",
        "Justificación": "Su disolución podría afectar la competitividad y percepción pública, pero el riesgo financiero es bajo.",
        "Controles a Implementar": "5.20: Abordar la seguridad de la información en los acuerdos con proveedores - Asegurar que las alianzas comerciales tengan acuerdos de seguridad.\n5.19: Seguridad de la información en las relaciones con proveedores - Supervisar la seguridad en las relaciones de alianza.\n5.7: Inteligencia sobre amenazas - Monitorear riesgos que puedan afectar las alianzas comerciales.",
        "Color Probabilidad": "Verde",
        "Color Impacto Financiero": "Verde",
        "Color Impacto Legal": "Verde",
        "Color Impacto Reputacional": "Amarillo"
    },
    {
        "N°": 36,
        "Activo": "Información del mercado",
        "Probabilidad": "Bajo",
        "Impacto Financiero": "Bajo",
        "Impacto Legal": "Bajo",
        "Impacto Reputacional": "Bajo",
        "Justificación": "Útil para estrategias, pero su pérdida o exposición tiene bajo impacto financiero, legal y reputacional.",
        "Controles a Implementar": "5.12: Clasificación de la información - Clasificar la información de mercado como confidencial o pública según su valor.\n8.11: Enmascaramiento de datos - Aplicar técnicas de enmascaramiento si se comparte información de mercado.\n5.34: Privacidad y protección de la PII - Asegurar la protección de cualquier dato personal en la información de mercado.",
        "Color Probabilidad": "Verde",
        "Color Impacto Financiero": "Verde",
        "Color Impacto Legal": "Verde",
        "Color Impacto Reputacional": "Verde"
    }
]